name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Instalar dependências
        run: npm install

      - name: Build do projeto
        run: npm run build

      - name: SCP Command to Transfer Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/dot7/browser/"
          target: ${{ secrets.DEPLOY_TARGET }}
          args: "-avz" # Sem o parâmetro --delete para preservar outros arquivos/pastas
